all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/ubuntu/kafka-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
    node_exporter_version: "1.8.2"
    node_exporter_port: 9100

  children:
    kafka_broker:
      hosts:
        10.0.1.7:
        10.0.1.244:
        10.0.2.185:
        10.0.2.91:

    kafka_controller:
      hosts:
        10.0.1.240:
        10.0.2.70:
        10.0.3.250:

    kafka_connect:
      hosts:
        10.0.1.80:

    observability:
      hosts:
        localhost:
          ansible_connection: local