{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Task Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_count{job=\"kafka-connect\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_count{job=~\"kafka-connect\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Startup Failure Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_task_startup_failure_total{job=~\"kafka-connect\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "min(kafka_connect_connect_metrics_incoming_byte_rate{job=~\"kafka-connect\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Startup Failure Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(kafka_connect_connect_worker_rebalance_metrics_rebalancing{job=~\"kafka-connect\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Rebalance Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "min(kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{job=~\"kafka-connect\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kafka_connect_connect_worker_metrics_task_startup_failure_total{job=\"kafka-connect\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "-1 * sum(kafka_connect_connect_metrics_outgoing_byte_rate{job=~\"kafka-connect\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}