{
 "title": "Kafka Dashboard",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\", role=~\"$role\"}, instance)"
    }
   },
   {
    "name": "role",
    "label": "role",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"$job\",role=\"broker\"} == 1)"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_newactivecontrollerscount{role=\"controller\"})"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount{instance=\"10.0.1.240:8079\"}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_replicascount{instance=~\"$instance\",role=\"$role\"})"
    }
   ]
  },
  {
   "title": "In-Sync Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_insyncreplicascount{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_globaltopiccount{role=\"controller\"})"
    }
   ]
  },
  {
   "title": "Message out per sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesoutpersec{instance=~'$instance'}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Byte in per sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesinpersec{instance=~'$instance'}[6h])/6) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_disk_io_now{}",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latest Offsets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"$job\", role=\"broker\"} == 1)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Oldest Offsets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_oldest_offset{instance=\"$instance\", topic=~\"$topic\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}